# ==========================================
# PUERTO DEL SERVIDOR
# ==========================================
server.port=${PORT:8080}

# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# ==========================================
# Ruta pública directa a tu MySQL en Railway con parámetros de seguridad
spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:24742/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Credenciales directas fijadas en el código
spring.datasource.username=root
spring.datasource.password=HdQvCiASsvPnyEVXQzBTJPyxppcbtTcr

# Driver de conexión
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect