# ==========================================
# PUERTO DEL SERVIDOR
# ==========================================
server.port=${PORT:8080}

# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# ==========================================
# Spring leerá las variables MYSQLHOST, MYSQLPORT, etc., que tienes en la captura
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# HIBERNATE / JPA (Creación automática de tablas)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect